temporary/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :flats
  root 'flats#index'
end

temporary/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :flats
end

temporary/app/models/flat.rb
class Flat < ActiveRecord::Base
	belongs_to :user
	belongs_to :category

  has_attached_file :flat_image, :styles => { :flat_index => "250x350>", :flat_show => "325x475>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :flat_image, :content_type => /\Aimage\/.*\Z/
end

temporary/app/models/user.rb
class User < ActiveRecord::Base
	has_many :flats
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

temporary/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

temporary/app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:category].blank?
  	 @flats = Flat.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @flats = Flat.where(:category_id => @category_id).order("created_at DESC")
    end
  end

  def new
  	@flat = current_user.flats.build
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def create
  	@flat = current_user.flats.build(flat_params)
    @flat.category_id = params[:category_id]

  	if @flat.save
  		redirect_to @flat
  	else
  		render 'new'
  	end
  end

  def show
  end

  def edit
    @categories = Category.all.map{ |c| [c.name, c.id]}
  end

  def update
    @flat.category_id = params[:category_id]
  	if @flat.update(flat_params)
  		redirect_to @flat
  	else
  		render 'edit'
  	end
  end

  def destroy
  	@flat.destroy
  	redirect_to root_path
  end

  private

  def find_flat
  	@flat = Flat.find(params[:id])
  end


  def flat_params
  	params.require(:flat).permit(:title, :description, :plz, :town, :category_id, :flat_image)
  end
end

temporary/app/helpers/application_helper.rb
module ApplicationHelper
end

temporary/app/helpers/flats_helper.rb
module FlatsHelper
end

temporary/app/views/flats/_form.html.erb
<%= simple_form_for @flat, :html => { :multipart => true } do |f| %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Kategorie") %>
	<%= f.input :title, label: "Titel" %>
	<%= f.input :discription, label: "Beschreibung" %>
	<%= f.input :plz, label: "Postleitzahl" %>
	<%= f.input :town, town: "Ort" %>
	<%= f.file_field :flat_image %>
	<%= f.submit "Veröffentlichen", :class => "btn-custom2" %>
	<% end %>

	

temporary/app/views/flats/edit.html.erb
<div class="col-md-8 col-md-offset-2">
	<div class="new-flat-form">

		<h1>Inserat überarbeiten</h1>

		<%= simple_form_for @flat, :html => { :multipart => true } do |f| %>
			<%= f.select :category_id, @categories %>
			<%= f.input :title, label: "Titel" %>
			<%= f.input :discription, label: "Beschreibung" %>
			<%= f.input :plz, label: "Postleitzahl" %>
			<%= f.input :town, label: "Ort" %>
			<%= f.file_field :flat_image %>
			<%= f.submit "Inserat aktualisieren", :class => "btn-custom2" %>
			<% end %>
	</div>
</div>

temporary/app/views/flats/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @flats.count == 0 %>
<h2>Momentan sind keine Einträge für diese Kategorie vorhanden.</h2>
<% else %>

<div class="row">

<% @flats.each do |flat| %>
<div class="col-md-3">
		<div><h2 class="flat-title"><%= link_to flat.title, flat_path(flat) %></h2></div>
		<div><a href="/flats/<%= flat.id %>">
			<%= image_tag flat.flat_image.url(:flat_index), class: "flat" %> </a></div>
		<div class="flat-author"><%= flat.plz %> <%= flat.town %></div> 
		<div class="flat-desc"><%= truncate(flat.discription, :length => 100) %></div>
	</div>
	<% end %>
</div>

<% end %>

temporary/app/views/flats/new.html.erb
<div class="col-md-8 col-md-offset-2">
	<div class="new-flat-form">
		<h1>Temporäre Wohnung erfassen</h1>

		<%= render 'form' %>
	</div>
</div>

temporary/app/views/flats/show.html.erb
<div class="row">
	<div class="col-md-4">
		
		<%= image_tag @flat.flat_image.url(:flat_show), class: "flat-show" %>
	</div>

	<div class="col-md-8">

		<div class="flat-info">
		<div class="message-show"><h1><%= @flat.title %></h1></div>
		<div class="flat-author">Erstellt vor <%= time_ago_in_words (@flat.created_at) %> </div>
		<div class="flat-author"> <%= @flat.plz %> <%= @flat.town %> </div>
		<div class="flat-desc"> <%= @flat.discription %></div>
		<div class="flat-author">Kategorie: <%= @flat.category.name %></div>
		</div>

		<div class="links btn-group">
		<%= link_to "Zurück", root_path, class: "btn btn-default"%>
		<% if user_signed_in? %>
		<% if @flat.user_id == current_user.id %>
			<%= link_to "Inserat überarbeiten", edit_flat_path(@flat), class: "btn btn-default" %>
			<%= link_to "Löschen", flat_path(@flat), method: :delete, data: {confirm: "Inserat wirklich löschen?"}, class: "btn btn-default" %>
			<% end %>
		<% end %>
		</div>
	</div>
</div>

temporary/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Temporary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header">
			<%= link_to "Startseite", root_path, class: "navbar-brand" %>
		</div>
		<ul class="nav navbar-nav">
			<li><%= link_to "Anmelden", new_user_registration_path %></li>
			<% if user_signed_in? %>
				<li><%= link_to "Ausloggen", destroy_user_session_path, method: :delete %></li>
			<% else %>
				<li><%= link_to "Einloggen", new_user_session_path %></li>
			<% end %>
		</ul>


		<ul class="nav navbar-nav navbar-right">

			<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Kategorie <span class="caret"></span></a>
			<ul class="dropdown-menu" role="menu">
				<% Category.all.each do |category| %>
					<li class="<%= 'active' if params[:category] == category.name %>"><%= link_to category.name, root_path(category: category.name), class: "link" %>
					</li>
				<% end %>
			</ul>
			</li>

			<% if user_signed_in? %>
				<li><%= link_to "Neue Wohnung erfassen", new_flat_path %></li>
			<% end %>
			
		</ul>

	</div>
</div>


<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="container">
<%= yield %>
</div>

</body>
</html>